=== HX35EU/HX35EUxmlGyak/DOMParseHX35EU/XMLSchemaHx35eu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="Webshop">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Vevő" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="TeljesNév" type="NevType"/>
                            <xs:element name="Telefonszám" type="TelefonszamType"/>
                            <xs:element name="Lakcím" type="LakcimType"/>
                        </xs:sequence>
                        <xs:attribute name="VEVO_ID" type="xs:integer" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Kosár" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attribute name="KOSAR_ID" type="xs:integer" use="required"></xs:attribute>
                        <xs:attribute name="VEVO_ID" type="xs:integer" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Termék" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Készlet" type="xs:integer"/>
                            <xs:element name="Megnevezés" type="xs:string"/>
                            <xs:element name="Ár" type="xs:integer"/>
                        </xs:sequence>
                        <xs:attribute name="TERMEK_ID" type="xs:integer" use="required"></xs:attribute>
                        <xs:attribute name="TIPUS_ID" type="xs:integer" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Típus" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Típusnév" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="TIPUS_ID" type="xs:integer" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="Benne" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Darab" type="xs:integer"/>
                            <xs:element name="Dátum" type="DatumType"/>
                        </xs:sequence>
                        <xs:attribute name="KOSAR_ID" type="xs:integer" use="required"></xs:attribute>
                        <xs:attribute name="TERMEK_ID" type="xs:integer" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
        <xs:key name="VEVO_KULCS">
            <xs:selector xpath="./Vevő" />
            <xs:field xpath="@VEVO_ID" />
        </xs:key>
        
        <xs:key name="KOSAR_KULCS">
            <xs:selector xpath="./Kosár" />
            <xs:field xpath="@KOSAR_ID" />
        </xs:key>
        
        <xs:key name="TERMEK_KULCS">
            <xs:selector xpath="./Termék" />
            <xs:field xpath="@TERMEK_ID" />
        </xs:key>
        
        <xs:key name="TIPUS_KULCS">
            <xs:selector xpath="./Típus"></xs:selector>
            <xs:field xpath="@TIPUS_ID"></xs:field>
        </xs:key>
        
        <xs:unique name="TERMEK_EGYEDI_KULCS">
            <xs:selector xpath="./Termék"></xs:selector>
            <xs:field xpath="@TERMEK_ID"></xs:field>
        </xs:unique>
        
        <xs:unique name="EGY_VEVO_EGY_KOSAR">
            <xs:selector xpath="./Kosár"></xs:selector>
            <xs:field xpath="@VEVO_ID"></xs:field>
        </xs:unique>
        
        <!-- Kosárhoz kötelező a vevő -->
        <xs:keyref name="VEVO_KOSARA" refer="VEVO_KULCS">
            <xs:selector xpath="./Kosár" />
            <xs:field xpath="@VEVO_ID" />
        </xs:keyref>
        
        <!-- Termékhez kötelező típus -->
        <xs:keyref name="TERMEK_TIPUSA" refer="TIPUS_KULCS">
            <xs:selector xpath="./Termék" />
            <xs:field xpath="@TIPUS_ID" />
        </xs:keyref>
        
        <!-- A kosár - termék kapcsolat megvalósítása -->
        <xs:keyref name="BENNE_KOSAR" refer="KOSAR_KULCS">
            <xs:selector xpath="./Benne" />
            <xs:field xpath="@KOSAR_ID" />
        </xs:keyref>
        
        <xs:keyref name="BENNE_TERMEK" refer="TERMEK_KULCS">
            <xs:selector xpath="./Benne" />
            <xs:field xpath="@TERMEK_ID" />
        </xs:keyref>
    </xs:element>
    
    <xs:simpleType name="IRSZType">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1000"/>
            <xs:maxInclusive value="9999"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TelefonszamType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(20|30|70)[0-9]{7}" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="DatumType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([12]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01]))" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="LakcimType">
        <xs:sequence>
            <xs:element name="Irányítószám" type="IRSZType"/>
            <xs:element name="Város" type="xs:string"/>
            <xs:element name="Utca" type="xs:string"/>
            <xs:element name="Házszám" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="NevType">
        <xs:sequence>
            <xs:element name="Vezetéknév" type="xs:string"/>
            <xs:element name="Keresztnév" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== HX35EU/HX35EUxmlGyak/DOMParseHX35EU/XMLHx35eu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Webshop xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaHx35eu.xsd">
    <Vevő VEVO_ID="0">
        <TeljesNév>
            <Vezetéknév>Szabó</Vezetéknév>
            <Keresztnév>Péter</Keresztnév>
        </TeljesNév>
        <Telefonszám>301234657</Telefonszám>
        <Lakcím>
            <Irányítószám>3524</Irányítószám>
            <Város>Miskolc</Város>
            <Utca>Stadion</Utca>
            <Házszám>12</Házszám>
        </Lakcím>
    </Vevő>
    <Vevő VEVO_ID="1">
        <TeljesNév>
            <Vezetéknév>Kiss</Vezetéknév>
            <Keresztnév>Béla Aurélió</Keresztnév>
        </TeljesNév>
        <Telefonszám>701234567</Telefonszám>
        <Lakcím>
            <Irányítószám>1015</Irányítószám>
            <Város>Budapest</Város>
            <Utca>Fahéj</Utca>
            <Házszám>22</Házszám>
        </Lakcím>
    </Vevő>
	<Vevő VEVO_ID="2">
        <TeljesNév>
            <Vezetéknév>Nincs</Vezetéknév>
            <Keresztnév>Ko Sara</Keresztnév>
        </TeljesNév>
        <Telefonszám>201234567</Telefonszám>
        <Lakcím>
            <Irányítószám>1015</Irányítószám>
            <Város>Budapest</Város>
            <Utca>Perec</Utca>
            <Házszám>10</Házszám>
        </Lakcím>
    </Vevő>
    <Kosár KOSAR_ID="0" VEVO_ID="0"/>
    <Kosár KOSAR_ID="1" VEVO_ID="1"/>
    <Termék TERMEK_ID="0" TIPUS_ID="0">
        <Készlet>12</Készlet>
        <Megnevezés>LG OLED88ZX9LA</Megnevezés>
		<Ár>110220</Ár>
    </Termék>
    <Termék TERMEK_ID="1" TIPUS_ID="0">
        <Készlet>5</Készlet>
        <Megnevezés>Samsung QE82Q950RB</Megnevezés>
		<Ár>142780</Ár>
    </Termék>
    <Termék TERMEK_ID="2" TIPUS_ID="2">
        <Készlet>120</Készlet>
        <Megnevezés>Apple iPhone 12 Pro Max</Megnevezés>
		<Ár>259160</Ár>
    </Termék>
    <Termék TERMEK_ID="3" TIPUS_ID="1">
        <Készlet>1</Készlet>
        <Megnevezés>Apple MacBook Pro 16</Megnevezés>
		<Ár>409420</Ár>
    </Termék>
    <Termék TERMEK_ID="4" TIPUS_ID="1">
        <Készlet>10</Készlet>
        <Megnevezés>Apple MacBook Pro 13</Megnevezés>
		<Ár>551100</Ár>
    </Termék>
    <Típus TIPUS_ID="0">
        <Típusnév>Televízió</Típusnév>
    </Típus>
    <Típus TIPUS_ID="1">
        <Típusnév>Laptop</Típusnév>
    </Típus>
    <Típus TIPUS_ID="2">
        <Típusnév>Mobiltelefon</Típusnév>
    </Típus>
    <Típus TIPUS_ID="3">
        <Típusnév>Tablet</Típusnév>
    </Típus>
    <Benne KOSAR_ID="0" TERMEK_ID="1">
        <Darab>2</Darab>
        <Dátum>2020-11-20</Dátum>
    </Benne>
    <Benne KOSAR_ID="0" TERMEK_ID="4">
        <Darab>1</Darab>
        <Dátum>2020-11-20</Dátum>
    </Benne>
    <Benne KOSAR_ID="0" TERMEK_ID="3">
        <Darab>10</Darab>
        <Dátum>2020-11-20</Dátum>
    </Benne>
</Webshop>
